configuration: Release

before_build:
  - nuget restore

version: '1.0.{build}'
  
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{appveyor_build_version}'
  
build:
  verbosity: normal
